package com.gk.services.rsrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-05-03T16:15:21.746+05:30
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://www.gk.com/schemas/rsrv", name = "IReservationService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IReservationService {

    @WebResult(name = "available", targetNamespace = "http://www.gk.com/schemas/rsrv", partName = "available")
    @WebMethod
    public boolean checkAvailability(
        @WebParam(partName = "onDate", name = "onDate", targetNamespace = "http://www.gk.com/schemas/rsrv")
        javax.xml.datatype.XMLGregorianCalendar onDate
    );

    @WebResult(name = "reservationId", targetNamespace = "http://www.gk.com/schemas/rsrv", partName = "reservationId")
    @WebMethod
    public java.lang.String makeReservation(
        @WebParam(partName = "reservationRequest", name = "reservationRequest", targetNamespace = "http://www.gk.com/schemas/rsrv")
        ReservationRequest reservationRequest
    );
}
