/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.gk.services.rsrv;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-05-03T16:15:21.545+05:30
 * Generated source version: 2.7.11
 */

@javax.jws.WebService(
		serviceName = "GKReservationService",
		portName = "GKReservationServicePort",
		targetNamespace = "http://www.gk.com/schemas/rsrv",
		wsdlLocation = "gkhotel.wsdl",
		endpointInterface = "com.gk.services.rsrv.IReservationService" )
public class IReservationServiceImpl implements IReservationService
{

	private static final Logger LOG = Logger.getLogger( IReservationServiceImpl.class.getName() );

	public boolean checkAvailability( javax.xml.datatype.XMLGregorianCalendar onDate )
	{
		LOG.info( "Executing operation checkAvailability" );
		System.out.println( onDate );
		try
		{
			boolean _return = false;
			return _return;
		}
		catch ( java.lang.Exception ex )
		{
			ex.printStackTrace();
			throw new RuntimeException( ex );
		}
	}

	/* (non-Javadoc)
	 * @see com.gk.services.rsrv.IReservationService#makeReservation(com.gk.services.rsrv.ReservationRequest  reservationRequest )*
	 */
	public java.lang.String makeReservation( ReservationRequest reservationRequest )
	{
		LOG.info( "Executing operation makeReservation" );
		System.out.println( reservationRequest );
		try
		{
			java.lang.String _return = "";
			return _return;
		}
		catch ( java.lang.Exception ex )
		{
			ex.printStackTrace();
			throw new RuntimeException( ex );
		}
	}

}
